import { execSync } from 'child_process';
import { readFileSync } from 'fs';
import { dirname, join } from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

/**
 * Get package version from package.json
 */
export function getPackageVersion() {
  try {
    const packageJsonPath = join(__dirname, '..', '..', 'package.json');
    const packageJson = JSON.parse(readFileSync(packageJsonPath, 'utf-8'));
    return packageJson.version || 'unknown';
  } catch (error) {
    return 'unknown';
  }
}

/**
 * Get current git commit hash (short form)
 */
export function getGitCommit() {
  try {
    return execSync('git rev-parse --short HEAD', { encoding: 'utf-8' }).trim();
  } catch (error) {
    return 'unknown';
  }
}

/**
 * Get git repository URL
 */
export function getGitRepoUrl() {
  try {
    const remoteUrl = execSync('git config --get remote.origin.url', { encoding: 'utf-8' }).trim();
    // Convert git@github.com:user/repo.git to https://github.com/user/repo
    if (remoteUrl.startsWith('git@github.com:')) {
      return remoteUrl
        .replace('git@github.com:', 'https://github.com/')
        .replace(/\.git$/, '');
    }
    // Already https URL, just remove .git suffix
    return remoteUrl.replace(/\.git$/, '');
  } catch (error) {
    return 'https://github.com/nlsherman-24861/claude-context-sync';
  }
}

/**
 * Generate metadata comment for generated files
 * @param {Object} options - Generation options
 * @param {string} options.format - Output format (claude-md, hybrid, chat)
 * @returns {string} HTML comment with generation metadata
 */
export function generateMetadata(options = {}) {
  const version = getPackageVersion();
  const commit = getGitCommit();
  const repoUrl = getGitRepoUrl();
  const timestamp = new Date().toISOString();
  const format = options.format || 'unknown';

  return `<!-- Generated by claude-context-sync v${version} (${commit}) on ${timestamp}
     Format: ${format}
     Source: ${repoUrl}

     This file is auto-generated. Do not edit manually.
     To update: Run 'claude-context-sync sync-repos' or regenerate from preferences.
-->`;
}
